export interface ZohoProductColor {
  hex: string;
  bg: string;
  bd: string;
  bg08: string;
  bd2: string;
}

export interface ZohoStat {
  value: string;
  label: string;
}

export interface ZohoProduct {
  slug: string;
  name: string;
  tagline: string;
  emoji: string;
  color: ZohoProductColor;
  lead: string;
  meta: {
    platform: string;
    deploy: string;
    extends: string;
  };
  stats: [ZohoStat, ZohoStat, ZohoStat];
  useCases: string[];
  bestFit: string;
  aiExtension?: string;
}

const blue: ZohoProductColor = {
  hex: '#6B9FD4',
  bg: 'rgba(107,159,212,.1)',
  bd: 'rgba(107,159,212,.25)',
  bg08: 'rgba(107,159,212,.08)',
  bd2: 'rgba(107,159,212,.2)',
};
const amber: ZohoProductColor = {
  hex: '#ECA934',
  bg: 'rgba(236,169,52,.1)',
  bd: 'rgba(236,169,52,.25)',
  bg08: 'rgba(236,169,52,.08)',
  bd2: 'rgba(236,169,52,.2)',
};
const purple: ZohoProductColor = {
  hex: '#8B9FD4',
  bg: 'rgba(139,159,212,.1)',
  bd: 'rgba(139,159,212,.25)',
  bg08: 'rgba(139,159,212,.08)',
  bd2: 'rgba(139,159,212,.2)',
};
const green: ZohoProductColor = {
  hex: '#4CAF50',
  bg: 'rgba(76,175,80,.1)',
  bd: 'rgba(76,175,80,.25)',
  bg08: 'rgba(76,175,80,.08)',
  bd2: 'rgba(76,175,80,.2)',
};

const aiExt =
  "We don't just deploy this app — we extend it with custom Claude AI agents, bespoke integrations, and Deluge scripts that make it do things the native platform can't. Your deployment is built exactly for your business.";

export const ZOHO_PRODUCTS: ZohoProduct[] = [
  {
    slug: 'crm',
    name: 'Zoho CRM',
    tagline: 'Close More. Chase Less.',
    emoji: '💼',
    color: blue,
    lead: 'Zoho CRM is the command centre for your entire sales operation. Manage leads, track deals, automate follow-ups, and get AI-powered insights — all in one place.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '500M+', label: 'Users Globally' },
      { value: '40%', label: 'Revenue Increase Avg' },
      { value: '3×', label: 'Faster Deal Close' },
    ],
    useCases: [
      'Lead scoring and qualification',
      'Pipeline management and forecasting',
      'Email and call logging automation',
      'Custom sales workflows and automation',
      'Canvas UI for client-facing portals',
    ],
    bestFit:
      'Sales teams, SDRs, account managers, and any business that needs to manage customer relationships at scale.',
    aiExtension: aiExt,
  },
  {
    slug: 'books',
    name: 'Zoho Books',
    tagline: 'Accounting That Runs Itself.',
    emoji: '📚',
    color: amber,
    lead: 'Full double-entry accounting with bank feeds, invoicing, expense tracking, and tax compliance — built for businesses outgrowing spreadsheets.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '100k+', label: 'Businesses' },
      { value: '15+', label: 'Tax Jurisdictions' },
      { value: 'Real-time', label: 'Bank Sync' },
    ],
    useCases: [
      'Invoicing and recurring billing',
      'Bank feeds and reconciliation',
      'Expense capture and approvals',
      'Sales tax / VAT / GST compliance',
      'Multi-currency consolidation',
    ],
    bestFit:
      'Finance teams at growth-stage companies that need accounting integrated with CRM, inventory, and operations.',
    aiExtension: aiExt,
  },
  {
    slug: 'analytics',
    name: 'Zoho Analytics',
    tagline: 'Decisions At The Speed Of Data.',
    emoji: '📊',
    color: purple,
    lead: 'A self-service BI and analytics platform that connects to 250+ sources. Build dashboards, find insights, and share intelligence across your team.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '250+', label: 'Data Sources' },
      { value: '500+', label: 'Visualizations' },
      { value: 'AI', label: 'Powered Insights' },
    ],
    useCases: [
      'Cross-system unified dashboards',
      'KPI and performance reporting',
      'Pipeline and revenue forecasting',
      'AI-driven anomaly detection',
      'Scheduled email reports',
    ],
    bestFit:
      'Operations, finance, and leadership teams who need a single live view across CRM, Books, Inventory, and third-party tools.',
    aiExtension: aiExt,
  },
  {
    slug: 'flow',
    name: 'Zoho Flow',
    tagline: 'Connect Everything. Automate Anything.',
    emoji: '🔄',
    color: blue,
    lead: 'A no-code integration platform that connects 800+ apps. Build multi-step workflows, automate handoffs, and stop copy-pasting between tools.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '800+', label: 'App Integrations' },
      { value: 'No-code', label: 'Builder' },
      { value: 'Logic', label: 'Branching & Loops' },
    ],
    useCases: [
      'Cross-app data sync',
      'Trigger-based workflow automation',
      'Webhook orchestration',
      'Conditional logic and branching',
      'Custom function steps',
    ],
    bestFit:
      'Any business running 5+ SaaS tools that wants a single automation layer connecting them.',
    aiExtension: aiExt,
  },
  {
    slug: 'desk',
    name: 'Zoho Desk',
    tagline: 'Support That Scales.',
    emoji: '🎧',
    color: amber,
    lead: 'A context-aware help desk with multi-channel ticketing, AI assistance, and deep CRM integration. Resolve issues faster with the full customer story in view.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '50k+', label: 'Companies' },
      { value: '5min', label: 'Avg First Response' },
      { value: 'AI Co-pilot', label: 'Zia' },
    ],
    useCases: [
      'Multi-channel ticket routing',
      'SLA tracking and escalation',
      'Self-service knowledge base',
      'Customer satisfaction surveys',
      'AI-suggested responses',
    ],
    bestFit:
      'Support teams handling email, chat, phone, and social — and any team that wants to escalate inside Slack.',
    aiExtension: aiExt,
  },
  {
    slug: 'sign',
    name: 'Zoho Sign',
    tagline: 'Contracts Signed In Minutes.',
    emoji: '✍️',
    color: blue,
    lead: 'Legally binding e-signatures with audit trails, templates, and workflow routing. Integrates directly with CRM, Books, and your contract repository.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'eIDAS', label: 'Compliant' },
      { value: '21 CFR', label: 'Part 11 Ready' },
      { value: '<1min', label: 'Avg Send Time' },
    ],
    useCases: [
      'Sales contract automation',
      'HR onboarding documents',
      'NDA and MSA workflows',
      'Bulk sending and templates',
      'Audit-grade signing trails',
    ],
    bestFit: 'Sales, HR, and legal teams that send contracts daily and need a faster turnaround.',
    aiExtension: aiExt,
  },
  {
    slug: 'projects',
    name: 'Zoho Projects',
    tagline: 'Ship Projects On Time.',
    emoji: '📋',
    color: purple,
    lead: 'Project management with Gantt charts, time tracking, and resource planning. Built for teams that bill by the hour or ship to deadlines.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Gantt', label: 'Native View' },
      { value: 'Time', label: 'Tracked Per Task' },
      { value: 'Billing', label: 'Integration' },
    ],
    useCases: [
      'Task and milestone tracking',
      'Resource and capacity planning',
      'Time tracking and timesheets',
      'Issue tracking and bug reports',
      'Billing and invoice generation',
    ],
    bestFit: 'Agencies, consultancies, and any team that needs to track time and bill clients.',
    aiExtension: aiExt,
  },
  {
    slug: 'inventory',
    name: 'Zoho Inventory',
    tagline: 'Stock In One System.',
    emoji: '📦',
    color: amber,
    lead: 'Multi-channel inventory management with real-time tracking, warehouse routing, and order fulfilment. Connects to Shopify, Amazon, eBay, and 3PLs.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Multi', label: 'Warehouse' },
      { value: 'Real-time', label: 'Stock Sync' },
      { value: '3PL', label: 'Integrations' },
    ],
    useCases: [
      'Multi-channel order management',
      'Warehouse and bin tracking',
      'Drop-ship and back-order workflows',
      'Serial / batch number tracking',
      'Reorder point automation',
    ],
    bestFit: 'E-commerce and distribution businesses managing stock across multiple channels and warehouses.',
    aiExtension: aiExt,
  },
  {
    slug: 'people',
    name: 'Zoho People',
    tagline: 'HR Done Right.',
    emoji: '👥',
    color: purple,
    lead: 'A full HRIS with employee records, leave tracking, performance reviews, and onboarding workflows. Compliant with US, EU, and APAC regulations.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '7k+', label: 'Companies' },
      { value: 'Multi', label: 'Country Payroll' },
      { value: 'Self-service', label: 'Portal' },
    ],
    useCases: [
      'Employee records and org chart',
      'Leave and time-off management',
      'Performance reviews and 1:1s',
      'Onboarding and offboarding flows',
      'HR analytics and reporting',
    ],
    bestFit: 'Growing teams (20+ employees) that need to systematise HR before it becomes a fire.',
    aiExtension: aiExt,
  },
  {
    slug: 'recruit',
    name: 'Zoho Recruit',
    tagline: 'Hire The Right People Faster.',
    emoji: '🎯',
    color: blue,
    lead: 'A modern ATS with sourcing, screening, interview scheduling, and offer management. Built for in-house recruiters and staffing agencies.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '60+', label: 'Job Boards' },
      { value: 'AI', label: 'Resume Parsing' },
      { value: 'Interview', label: 'Scheduling' },
    ],
    useCases: [
      'Job posting to multiple boards',
      'Candidate sourcing and pipeline',
      'Interview scheduling automation',
      'AI-assisted resume screening',
      'Offer letter and onboarding handoff',
    ],
    bestFit: 'In-house TA teams and staffing agencies running 5+ open roles at any time.',
    aiExtension: aiExt,
  },
  {
    slug: 'expense',
    name: 'Zoho Expense',
    tagline: 'Expenses Closed In Hours, Not Weeks.',
    emoji: '💳',
    color: amber,
    lead: 'Expense reporting with receipt OCR, corporate card feeds, mileage tracking, and policy enforcement. Reimburse faster, audit cleaner.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'OCR', label: 'Receipt Scan' },
      { value: 'Card', label: 'Feed Sync' },
      { value: 'Policy', label: 'Enforcement' },
    ],
    useCases: [
      'Mobile receipt capture',
      'Corporate card reconciliation',
      'Mileage and per diem tracking',
      'Multi-step approval workflows',
      'Direct integration with Zoho Books',
    ],
    bestFit: 'Finance teams that want to kill the monthly expense-report spreadsheet ritual.',
    aiExtension: aiExt,
  },
  {
    slug: 'creator',
    name: 'Zoho Creator',
    tagline: 'Build Apps Without Engineers.',
    emoji: '🛠',
    color: purple,
    lead: 'A low-code application platform for building custom business apps — forms, workflows, reports, and integrations — without traditional engineering cycles.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Low-code', label: 'Builder' },
      { value: 'Deluge', label: 'Scripting' },
      { value: 'Mobile', label: 'Native Apps' },
    ],
    useCases: [
      'Custom internal tools',
      'Field-service mobile apps',
      'Operations and approval workflows',
      'Data-collection forms',
      'Integrations the standard suite misses',
    ],
    bestFit: 'Ops and IT teams that need custom apps but lack engineering bandwidth.',
    aiExtension: aiExt,
  },
  {
    slug: 'bigin',
    name: 'Zoho Bigin',
    tagline: 'The Small-Team CRM.',
    emoji: '🌱',
    color: amber,
    lead: 'A pipeline-centric CRM for small businesses — without the complexity of full CRM. Set up in under an hour, master in a day.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '1hr', label: 'Setup Time' },
      { value: 'Pipeline', label: 'View First' },
      { value: 'Email', label: 'Sync Native' },
    ],
    useCases: [
      'Pipeline tracking',
      'Email and call logging',
      'Activity reminders',
      'Mobile-first sales execution',
      'Quick reporting',
    ],
    bestFit: 'Small teams (1–10 people) that need a CRM without the weight of a CRM.',
    aiExtension: aiExt,
  },
  {
    slug: 'forms',
    name: 'Zoho Forms',
    tagline: 'Forms That Power Workflows.',
    emoji: '📝',
    color: blue,
    lead: 'Online forms with conditional logic, payment fields, and 100+ integrations. Capture data, trigger workflows, populate CRM in one motion.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '40+', label: 'Field Types' },
      { value: 'Payment', label: 'Capture' },
      { value: '100+', label: 'Integrations' },
    ],
    useCases: [
      'Web inquiry forms',
      'Survey and feedback collection',
      'Event registration',
      'Payment capture',
      'Approval workflows',
    ],
    bestFit: 'Any business that captures inbound information online and routes it to CRM, email, or workflows.',
    aiExtension: aiExt,
  },
  {
    slug: 'salesiq',
    name: 'Zoho SalesIQ',
    tagline: 'See Visitors. Talk To Them. Close.',
    emoji: '💬',
    color: amber,
    lead: 'Live chat, visitor tracking, and chatbots for your website. See who is on your site in real time and engage them at the right moment.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Real-time', label: 'Visitor Tracking' },
      { value: 'Chatbot', label: 'Builder' },
      { value: 'CRM', label: 'Push Native' },
    ],
    useCases: [
      'Live chat and proactive triggers',
      'Visitor identification and scoring',
      'AI chatbot deployment',
      'Lead capture and CRM push',
      'Chat-to-call escalation',
    ],
    bestFit: 'Sales-led businesses that get traffic on their site and want to identify high-intent visitors.',
    aiExtension: aiExt,
  },
  {
    slug: 'campaigns',
    name: 'Zoho Campaigns',
    tagline: 'Email Marketing That Converts.',
    emoji: '📧',
    color: purple,
    lead: 'Drag-and-drop email builder with automation, A/B testing, and deep CRM segmentation. Run nurture, broadcast, and transactional campaigns from one place.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '250+', label: 'Templates' },
      { value: 'Journey', label: 'Automation' },
      { value: 'CRM', label: 'Native Sync' },
    ],
    useCases: [
      'Nurture and drip campaigns',
      'Broadcast newsletters',
      'A/B testing and optimization',
      'Segment-based targeting',
      'Engagement scoring',
    ],
    bestFit: 'Marketing teams running email at scale alongside CRM and analytics.',
    aiExtension: aiExt,
  },
  {
    slug: 'social',
    name: 'Zoho Social',
    tagline: 'Manage Every Channel In One Place.',
    emoji: '📱',
    color: blue,
    lead: 'Schedule posts, monitor conversations, and analyse engagement across LinkedIn, X, Facebook, Instagram, and more.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '7+', label: 'Channels' },
      { value: 'Scheduling', label: 'Bulk + Smart' },
      { value: 'Reports', label: 'Built-in' },
    ],
    useCases: [
      'Multi-channel post scheduling',
      'Engagement and inbox management',
      'Brand monitoring',
      'Team collaboration on posts',
      'Performance analytics',
    ],
    bestFit: 'In-house marketing teams managing 3+ social channels.',
    aiExtension: aiExt,
  },
  {
    slug: 'survey',
    name: 'Zoho Survey',
    tagline: 'Ask Better Questions.',
    emoji: '📋',
    color: purple,
    lead: 'Build branded surveys with conditional logic, NPS scoring, and analytics. Distribute via email, embed, or QR code.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '25+', label: 'Question Types' },
      { value: 'NPS', label: 'Built-in' },
      { value: 'Branching', label: 'Logic' },
    ],
    useCases: [
      'Customer satisfaction (CSAT/NPS)',
      'Employee engagement surveys',
      'Market research',
      'Event feedback',
      'Product research',
    ],
    bestFit: 'Any team that runs structured feedback collection.',
    aiExtension: aiExt,
  },
  {
    slug: 'marketingplus',
    name: 'Zoho Marketing Plus',
    tagline: 'One Hub For All Of Marketing.',
    emoji: '🎯',
    color: amber,
    lead: 'A unified marketing platform combining email, social, surveys, webinars, and analytics in one workspace.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '9', label: 'Apps Unified' },
      { value: 'Campaigns', label: 'Cross-channel' },
      { value: 'Unified', label: 'Reporting' },
    ],
    useCases: [
      'Cross-channel campaign orchestration',
      'Unified audience segmentation',
      'Multi-team marketing collaboration',
      'Single-source attribution',
      'Brand asset management',
    ],
    bestFit: 'Mid-market marketing teams running 4+ channels who want one workspace.',
    aiExtension: aiExt,
  },
  {
    slug: 'sites',
    name: 'Zoho Sites',
    tagline: 'Websites Without The Webmaster.',
    emoji: '🌐',
    color: blue,
    lead: 'A drag-and-drop website builder for marketing sites and microsites. Native integration with CRM forms and Campaigns.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Drag', label: 'Drop Builder' },
      { value: 'Hosted', label: 'Managed' },
      { value: 'SEO', label: 'Tools Native' },
    ],
    useCases: [
      'Marketing landing pages',
      'Company websites',
      'Microsite campaigns',
      'Blog and content publishing',
      'Member portals',
    ],
    bestFit: "Teams that need a marketing site but don't want to manage WordPress hosting.",
    aiExtension: aiExt,
  },
  {
    slug: 'landingpage',
    name: 'Zoho LandingPage',
    tagline: 'Convert Visitors Into Leads.',
    emoji: '🎯',
    color: purple,
    lead: 'High-converting landing pages with built-in A/B testing, popups, and lead capture flowing straight into CRM.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '100+', label: 'Templates' },
      { value: 'A/B', label: 'Built-in Tests' },
      { value: 'Heatmaps', label: 'Native' },
    ],
    useCases: [
      'Campaign landing pages',
      'Lead-magnet downloads',
      'Webinar registration',
      'A/B testing offers',
      'Quick microsite spin-up',
    ],
    bestFit: 'Performance marketers running paid campaigns who need fast page iteration.',
    aiExtension: aiExt,
  },
  {
    slug: 'backstage',
    name: 'Zoho Backstage',
    tagline: 'Run Events That Convert.',
    emoji: '🎤',
    color: blue,
    lead: 'End-to-end event management for in-person, virtual, and hybrid events — registration, ticketing, agenda, sponsors, and analytics.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'In-person', label: 'Virtual + Hybrid' },
      { value: 'Mobile', label: 'Event App' },
      { value: 'CRM', label: 'Native Sync' },
    ],
    useCases: [
      'Conference registration and ticketing',
      'Virtual event streaming',
      'Hybrid event coordination',
      'Sponsor and exhibitor management',
      'Attendee networking',
    ],
    bestFit: 'Companies running 2+ events per year that want a single platform.',
    aiExtension: aiExt,
  },
  {
    slug: 'webinar',
    name: 'Zoho Webinar',
    tagline: 'Webinars That Generate Pipeline.',
    emoji: '📡',
    color: purple,
    lead: 'Webinar hosting with registration pages, polls, Q&A, and direct CRM integration for lead capture and follow-up.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'HD', label: 'Streaming' },
      { value: 'Polls', label: 'Q&A Built-in' },
      { value: 'CRM', label: 'Sync Auto' },
    ],
    useCases: [
      'Demand-gen webinars',
      'Customer onboarding sessions',
      'Product launches',
      'Internal training',
      'Recurring office hours',
    ],
    bestFit: 'B2B marketing and sales teams that run webinars as a primary pipeline source.',
    aiExtension: aiExt,
  },
  {
    slug: 'pagesense',
    name: 'Zoho PageSense',
    tagline: 'Watch Visitors. Improve Conversion.',
    emoji: '🔍',
    color: blue,
    lead: 'A/B testing, heatmaps, session recordings, and funnel analysis. See what visitors actually do on your site and fix the friction.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Heatmaps', label: 'Click + Scroll' },
      { value: 'Recordings', label: 'Session' },
      { value: 'A/B', label: 'Personalize' },
    ],
    useCases: [
      'Conversion-rate optimization',
      'Click and scroll heatmaps',
      'Session replay',
      'Funnel drop-off analysis',
      'Form analytics',
    ],
    bestFit: 'Marketing and product teams optimising web funnels.',
    aiExtension: aiExt,
  },
  {
    slug: 'commerce',
    name: 'Zoho Commerce',
    tagline: 'Storefronts That Sell.',
    emoji: '🛒',
    color: amber,
    lead: 'A full e-commerce platform with payments, inventory, shipping, and marketing — natively connected to Zoho CRM and Books.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: '40+', label: 'Payment Gateways' },
      { value: 'Inventory', label: 'Native Sync' },
      { value: 'SEO', label: 'Optimised' },
    ],
    useCases: [
      'B2C and B2B online stores',
      'Subscription commerce',
      'Multi-currency pricing',
      'Inventory and shipping orchestration',
      'Cart abandonment recovery',
    ],
    bestFit: 'Brands selling DTC who want commerce, inventory, and accounting in one stack.',
    aiExtension: aiExt,
  },
  {
    slug: 'thrive',
    name: 'Zoho Thrive',
    tagline: 'Affiliate Growth On Autopilot.',
    emoji: '🚀',
    color: amber,
    lead: 'Loyalty, referral, and affiliate program management. Reward customers, partners, and advocates for driving revenue.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Loyalty', label: '+ Referral' },
      { value: 'Affiliate', label: 'Tracking' },
      { value: 'Rewards', label: 'Multi-tier' },
    ],
    useCases: [
      'Customer loyalty programs',
      'Referral campaigns',
      'Affiliate revenue tracking',
      'Tiered reward structures',
      'Partner enablement',
    ],
    bestFit: 'D2C brands and SaaS companies running affiliate or loyalty motions.',
    aiExtension: aiExt,
  },
  {
    slug: 'mail',
    name: 'Zoho Mail',
    tagline: 'Business Email That Just Works.',
    emoji: '✉️',
    color: blue,
    lead: 'Business-grade email with custom domains, calendar, tasks, and team collaboration. Privacy-first and ad-free.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Ad-free', label: 'Privacy First' },
      { value: 'Calendar', label: 'Native' },
      { value: 'Custom', label: 'Domain' },
    ],
    useCases: [
      'Business email hosting',
      'Team calendars',
      'Task management',
      'Shared inboxes',
      'Custom domain DNS',
    ],
    bestFit: 'Businesses tired of Gmail/Outlook surveillance who want a private alternative.',
    aiExtension: aiExt,
  },
  {
    slug: 'cliq',
    name: 'Zoho Cliq',
    tagline: 'Team Chat. No Distraction.',
    emoji: '💬',
    color: blue,
    lead: 'Team messaging with channels, threads, video calls, and bots. Slack-style collaboration inside the Zoho ecosystem.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Channels', label: '+ DMs' },
      { value: 'Video', label: 'HD Calls' },
      { value: 'Bots', label: 'Custom + API' },
    ],
    useCases: [
      'Team channels and threads',
      'Video and voice calls',
      'Custom bot integrations',
      'File sharing and search',
      'Zoho-app shortcuts',
    ],
    bestFit: 'Zoho One customers who want chat without paying for a separate Slack license.',
    aiExtension: aiExt,
  },
  {
    slug: 'meeting',
    name: 'Zoho Meeting',
    tagline: 'Meet. Record. Move On.',
    emoji: '🎥',
    color: blue,
    lead: 'HD video conferencing with recording, transcripts, screen sharing, and Outlook/Calendar integration.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'HD', label: 'Video' },
      { value: 'Recording', label: '+ Transcript' },
      { value: 'Calendar', label: 'Integration' },
    ],
    useCases: [
      'Internal team meetings',
      'Customer demos',
      'Webinars and trainings',
      'Recorded handoffs',
      'Outlook/Google scheduling',
    ],
    bestFit: 'Teams that want Zoom-style meetings without a separate Zoom bill.',
    aiExtension: aiExt,
  },
  {
    slug: 'workdrive',
    name: 'Zoho WorkDrive',
    tagline: 'Files That Stay In Sync.',
    emoji: '📁',
    color: purple,
    lead: 'Team file storage with version control, permissions, and external sharing. The Google Drive alternative inside Zoho One.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Team', label: 'Folders' },
      { value: 'Permissions', label: 'Granular' },
      { value: 'External', label: 'Sharing' },
    ],
    useCases: [
      'Team document storage',
      'Versioned file collaboration',
      'External client sharing',
      'Approvals and review',
      'Native office editing',
    ],
    bestFit: 'Teams that need shared file storage without licensing Google Workspace.',
    aiExtension: aiExt,
  },
  {
    slug: 'writer',
    name: 'Zoho Writer',
    tagline: 'Documents Built For Workflows.',
    emoji: '📄',
    color: purple,
    lead: 'A modern word processor with mail merge, e-sign, document automation, and AI writing assistance.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Mail', label: 'Merge Native' },
      { value: 'e-Sign', label: 'Inline' },
      { value: 'AI', label: 'Writing Help' },
    ],
    useCases: [
      'Document drafting and collaboration',
      'Mail merge from CRM data',
      'Contract templates with merge fields',
      'Inline e-sign workflows',
      'Document automation',
    ],
    bestFit: 'Sales, HR, and legal teams that produce template-heavy documents.',
    aiExtension: aiExt,
  },
  {
    slug: 'sheet',
    name: 'Zoho Sheet',
    tagline: 'Spreadsheets For Teams.',
    emoji: '📊',
    color: purple,
    lead: 'Cloud spreadsheets with real-time collaboration, advanced formulas, and Deluge scripting for automation.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Real-time', label: 'Collab' },
      { value: '350+', label: 'Functions' },
      { value: 'Scripting', label: 'Deluge' },
    ],
    useCases: [
      'Financial models',
      'Operational dashboards',
      'Data analysis',
      'Forecast templates',
      'Scripted automation',
    ],
    bestFit: 'Teams that live in spreadsheets but want them connected to Zoho data.',
    aiExtension: aiExt,
  },
  {
    slug: 'show',
    name: 'Zoho Show',
    tagline: 'Presentations Without The Pain.',
    emoji: '🎬',
    color: purple,
    lead: 'Cloud presentation software with real-time collaboration, brand templates, and broadcaster mode.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Templates', label: 'Brand Locked' },
      { value: 'Real-time', label: 'Collab' },
      { value: 'Broadcast', label: 'Mode' },
    ],
    useCases: [
      'Pitch decks',
      'Investor and board presentations',
      'Customer-facing decks',
      'Internal town halls',
      'Branded templates',
    ],
    bestFit: 'Sales and leadership teams that present often and want brand consistency.',
    aiExtension: aiExt,
  },
  {
    slug: 'notebook',
    name: 'Zoho Notebook',
    tagline: 'Notes That Don’t Get Lost.',
    emoji: '📓',
    color: purple,
    lead: 'A clean, fast notes app with audio, photo, sketch, and checklist cards. Syncs across web, desktop, and mobile.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Sync', label: 'All Devices' },
      { value: 'Cards', label: 'Multi-format' },
      { value: 'Search', label: 'Universal' },
    ],
    useCases: [
      'Personal note-taking',
      'Meeting capture',
      'Audio memos',
      'Sketches and visual notes',
      'Quick reference library',
    ],
    bestFit: 'Anyone who needs a private notes app that beats Apple Notes.',
    aiExtension: aiExt,
  },
  {
    slug: 'connect',
    name: 'Zoho Connect',
    tagline: 'Your Company’s Private Network.',
    emoji: '🔗',
    color: blue,
    lead: 'A private social network for your team — announcements, channels, forums, and a company directory in one place.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Feed', label: 'Company-wide' },
      { value: 'Forums', label: '+ Groups' },
      { value: 'Directory', label: 'People Native' },
    ],
    useCases: [
      'Company announcements',
      'Internal forums and Q&A',
      'Employee directory',
      'Knowledge sharing',
      'Town-hall posts',
    ],
    bestFit: 'Mid-size companies (50+ employees) trying to scale internal communication.',
    aiExtension: aiExt,
  },
  {
    slug: 'teaminbox',
    name: 'Zoho TeamInbox',
    tagline: 'Shared Inboxes Done Right.',
    emoji: '📨',
    color: blue,
    lead: 'Team-shared email inboxes with assignment, internal comments, and threaded collaboration. Treat support@ like a CRM.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Assign', label: '+ Comment' },
      { value: 'Threading', label: 'Native' },
      { value: 'Filters', label: 'Auto-route' },
    ],
    useCases: [
      'Shared support@ inbox',
      'Sales-team inbox triage',
      'Hiring and recruiting inboxes',
      'Internal notes per thread',
      'Assignment and SLA tracking',
    ],
    bestFit: 'Teams that share a single email address and need accountability.',
    aiExtension: aiExt,
  },
  {
    slug: 'bookings',
    name: 'Zoho Bookings',
    tagline: 'Stop Trading Calendar Emails.',
    emoji: '📅',
    color: blue,
    lead: 'A scheduling app for sales calls, demos, support, and recruiting — with payment capture and CRM sync.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Calendar', label: 'Sync All' },
      { value: 'Payment', label: 'On Booking' },
      { value: 'CRM', label: 'Native Push' },
    ],
    useCases: [
      'Discovery and demo booking',
      'Customer support appointments',
      'Recruiting interview slots',
      'Service appointments with payment',
      'Round-robin team scheduling',
    ],
    bestFit: 'Customer-facing teams that book calls daily and want Calendly without paying for it twice.',
    aiExtension: aiExt,
  },
  {
    slug: 'learn',
    name: 'Zoho Learn',
    tagline: 'Knowledge That Compounds.',
    emoji: '🎓',
    color: purple,
    lead: 'A learning management and knowledge base platform for internal training, customer education, and certifications.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'LMS', label: '+ Knowledge Base' },
      { value: 'Quizzes', label: 'Native' },
      { value: 'Cert', label: 'Tracks' },
    ],
    useCases: [
      'Employee onboarding training',
      'Customer education',
      'Internal knowledge base',
      'Certification tracks',
      'Onboarding paths',
    ],
    bestFit: 'Growing companies that need to systematise training before scaling headcount.',
    aiExtension: aiExt,
  },
  {
    slug: 'lens',
    name: 'Zoho Lens',
    tagline: 'See What They See.',
    emoji: '👁',
    color: blue,
    lead: 'Augmented-reality remote assistance — see through the customer’s camera and annotate live to guide field service.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'AR', label: 'Annotation' },
      { value: 'Live', label: 'Camera Stream' },
      { value: 'Multi', label: 'Platform App' },
    ],
    useCases: [
      'Remote technician support',
      'Field service troubleshooting',
      'Installation guidance',
      'Insurance claim inspection',
      'On-site product assistance',
    ],
    bestFit: 'Service businesses with field technicians or remote installs.',
    aiExtension: aiExt,
  },
  {
    slug: 'invoice',
    name: 'Zoho Invoice',
    tagline: 'Invoices Free Forever.',
    emoji: '🧾',
    color: amber,
    lead: 'A clean invoicing app with timesheets, expense capture, and payment links. Free for small businesses.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Free', label: 'Forever' },
      { value: 'Timesheet', label: 'Native' },
      { value: 'Payment', label: 'Links' },
    ],
    useCases: [
      'Client invoicing',
      'Hourly billing and timesheets',
      'Recurring invoices',
      'Expense reimbursement',
      'Payment-link collection',
    ],
    bestFit: 'Freelancers and small businesses below the Zoho Books threshold.',
    aiExtension: aiExt,
  },
  {
    slug: 'billing',
    name: 'Zoho Billing',
    tagline: 'Subscription Billing That Scales.',
    emoji: '💰',
    color: amber,
    lead: 'Subscription billing, dunning, revenue recognition, and quote-to-cash automation for SaaS and recurring businesses.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Subscription', label: 'Lifecycle' },
      { value: 'Dunning', label: 'Automated' },
      { value: 'Revenue', label: 'Recognition' },
    ],
    useCases: [
      'Subscription pricing and plans',
      'Trial and dunning automation',
      'Quote-to-cash workflows',
      'Revenue recognition',
      'Multi-currency subscriptions',
    ],
    bestFit: 'SaaS and recurring-revenue businesses that need real subscription billing.',
    aiExtension: aiExt,
  },
  {
    slug: 'checkout',
    name: 'Zoho Checkout',
    tagline: 'Payments In Minutes.',
    emoji: '💳',
    color: amber,
    lead: 'Hosted payment pages and one-off invoicing links — no developer required.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Hosted', label: 'Page Builder' },
      { value: 'Recurring', label: 'or One-off' },
      { value: 'Multi', label: 'Gateway' },
    ],
    useCases: [
      'One-off payment links',
      'Donation pages',
      'Quick checkout flows',
      'Subscription sign-up pages',
      'Custom-branded payment portals',
    ],
    bestFit: 'Anyone who needs to take payment without building a store.',
    aiExtension: aiExt,
  },
  {
    slug: 'sprints',
    name: 'Zoho Sprints',
    tagline: 'Agile Without The Ceremony.',
    emoji: '⚡',
    color: purple,
    lead: 'A clean agile/scrum tool with backlogs, sprint planning, scrum boards, and burndowns — built for product and engineering teams.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Backlog', label: '+ Sprints' },
      { value: 'Boards', label: 'Scrum + Kanban' },
      { value: 'Burndown', label: 'Native' },
    ],
    useCases: [
      'Agile/Scrum sprint planning',
      'Backlog grooming',
      'Burndown and velocity reporting',
      'Daily stand-ups',
      'Cross-team release tracking',
    ],
    bestFit: 'Product and engineering teams that want Jira without the weight.',
    aiExtension: aiExt,
  },
  {
    slug: 'assist',
    name: 'Zoho Assist',
    tagline: 'Remote Support, Instantly.',
    emoji: '🖥',
    color: blue,
    lead: 'Web-based remote desktop and unattended access for IT support, customer service, and field technicians.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Browser', label: 'No Install' },
      { value: 'Unattended', label: 'Access' },
      { value: 'Multi-platform', label: 'Windows/Mac/Lnx' },
    ],
    useCases: [
      'Remote IT support',
      'Customer remote assistance',
      'Unattended server administration',
      'Multi-monitor sessions',
      'File transfer during session',
    ],
    bestFit: 'IT teams and service businesses that support customer machines remotely.',
    aiExtension: aiExt,
  },
  {
    slug: 'dataprep',
    name: 'Zoho DataPrep',
    tagline: 'Clean Data. Good Decisions.',
    emoji: '🧹',
    color: purple,
    lead: 'A self-service data prep tool — cleanse, transform, enrich, and pipe data into Analytics, Books, CRM, or external warehouses.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'No-code', label: 'Transform' },
      { value: 'Enrich', label: '+ Cleanse' },
      { value: 'Pipeline', label: 'Scheduled' },
    ],
    useCases: [
      'Data cleansing and de-dup',
      'Format standardisation',
      'Multi-source enrichment',
      'Scheduled ETL pipelines',
      'Pre-analytics preparation',
    ],
    bestFit: 'Analytics and ops teams who need clean data without an engineering team.',
    aiExtension: aiExt,
  },
  {
    slug: 'apptics',
    name: 'Zoho Apptics',
    tagline: 'Know What Users Do In Your App.',
    emoji: '📈',
    color: blue,
    lead: 'A privacy-focused mobile and web app analytics platform with event tracking, funnels, and crash reporting.',
    meta: { platform: 'Standalone', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'Privacy', label: 'GDPR/CCPA' },
      { value: 'Funnels', label: '+ Cohorts' },
      { value: 'Crash', label: 'Reporting' },
    ],
    useCases: [
      'Mobile app analytics',
      'Web app event tracking',
      'Funnel and retention analysis',
      'Crash and error monitoring',
      'A/B variant tracking',
    ],
    bestFit: 'Mobile-app and SaaS teams that want product analytics without Mixpanel pricing.',
    aiExtension: aiExt,
  },
  {
    slug: 'contracts',
    name: 'Zoho Contracts',
    tagline: 'Contracts From Draft To Signature.',
    emoji: '📜',
    color: amber,
    lead: 'A contract lifecycle management platform — drafting, redlining, approvals, signature, and renewal workflows in one place.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'CLM', label: 'Full Lifecycle' },
      { value: 'Redline', label: '+ Approval' },
      { value: 'Renewal', label: 'Auto Track' },
    ],
    useCases: [
      'Drafting and templates',
      'Redlining and version control',
      'Approval workflows',
      'Native e-sign integration',
      'Renewal and obligation tracking',
    ],
    bestFit: 'Mid-market and enterprise legal/sales teams that handle 20+ contracts per month.',
    aiExtension: aiExt,
  },
  {
    slug: 'vault',
    name: 'Zoho Vault',
    tagline: 'Passwords. Safe. Shared.',
    emoji: '🔐',
    color: green,
    lead: 'A team password manager with secure sharing, granular permissions, and admin policies. Enterprise-grade vaulting at small-business price.',
    meta: { platform: 'Zoho One', deploy: 'Yes', extends: 'Claude AI' },
    stats: [
      { value: 'AES-256', label: 'Encryption' },
      { value: 'SSO', label: '+ MFA' },
      { value: 'Audit', label: 'Logs Full' },
    ],
    useCases: [
      'Team password sharing',
      'Shared admin credentials',
      'Onboarding and offboarding access',
      'SSO and 2FA enforcement',
      'Audit trail of credential access',
    ],
    bestFit: 'Any team that still emails passwords. (Stop doing that.)',
    aiExtension: aiExt,
  },
];

export function getZohoProduct(slug: string): ZohoProduct | undefined {
  return ZOHO_PRODUCTS.find((p) => p.slug === slug);
}

export const ZOHO_PRODUCT_SLUGS = ZOHO_PRODUCTS.map((p) => p.slug);
